import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import BoxPost from '@/components/BoxPost'
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import { useQuery } from 'react-query';
export default function Home() {
  const { isLoading, error, data } = useQuery('posts',
    () => fetch('https://jsonplaceholder.typicode.com/posts').then((res) => {
      return res.json()
    })
  )
  console.log(isLoading)
  console.log(data)
  if (isLoading) return 'Loading...'
  if (error) return 'An error has occurred: ' + error
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Grid container spacing={2}>
          <Grid item md={4}>
            <BoxPost />
          </Grid>
        </Grid>
      </Container>
    </>
  )
}
