import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import BoxPost from '@/components/BoxPost'
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import { useQuery, QueryClient, dehydrate } from "react-query"
import { GetStaticProps, } from "next"// import { fetchPosts } from '@/components/fetchPosts';
import Link from 'next/link';


export const getStaticProps: GetStaticProps = async (context) => {

  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(["posts"],
      () => fetch(`https://jsonplaceholder.typicode.com/posts`).then((res) => {
          return res.json()
      })
  );
  console.log('[id]:13', dehydrate(queryClient))
  return {
      props: {
          dehydratedState: dehydrate(queryClient)
      }
  };
};

export default function Home(props:any) {
  console.log(props)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Grid container spacing={2}>
          <Grid item md={4}>
            <Link href='/post/1'>
              <BoxPost />
            </Link>

          </Grid>
        </Grid>
      </Container>
    </>
  )
}
