import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import BoxPost from '@/components/BoxPost'
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import { useQuery, QueryClient, dehydrate } from "react-query"
import { GetStaticProps, } from "next"// import { fetchPosts } from '@/components/fetchPosts';
import Link from 'next/link';
import fetchPost from '@/components/fetchPosts';



export const getStaticProps: GetStaticProps = async () => {

  const queryClient = new QueryClient();
  await queryClient.prefetchQuery(['posts'], () => fetchPost());
  return {
    props: {
      dehydratedState: dehydrate(queryClient)
    }
  };
};

export default function Home() {
  const { data, isLoading } = useQuery(['post'], () => fetchPost());
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Grid container spacing={2}>
          {isLoading ? 'Loading ...' : data.map((item: any) => {
            return (
              <Grid key={item.id} item md={4}>
                <Link shallow={true} href={`/post/${item.id}`}>
                  <BoxPost {...item} />
                </Link>
              </Grid>
            )
          })}
        </Grid>
      </Container>
    </>
  )
}
